// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Nav': string;
  'Nav__item': string;
  'Nav__item_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
