// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'RecommendedResources': string;
  'RecommendedResources__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
