// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourcePreviewInfo': string;
  'ResourcePreviewInfo__data': string;
  'ResourcePreviewInfo__favicon': string;
  'ResourcePreviewInfo__source': string;
  'ResourcePreviewInfo__source_site': string;
  'ResourcePreviewInfo__title': string;
  'ResourcePreviewInfo__type': string;
}
declare var cssExports: CssExports;
export = cssExports;
