// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Tip': string;
  'Tip__icon': string;
  'Tip__icon_info': string;
  'Tip__icon_lock': string;
}
declare var cssExports: CssExports;
export = cssExports;
