// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ShowCheckbox': string;
  'SkillsSearch': string;
  'SkillsSearch__body': string;
  'SkillsSearch__checkbox': string;
  'SkillsSearch__checkbox_header': string;
  'SkillsSearch__content': string;
  'SkillsSearch__footer': string;
  'SkillsSearch__header': string;
  'SkillsSearch__input': string;
  'SkillsSearch__row': string;
  'SkillsSearch__submit': string;
}
declare var cssExports: CssExports;
export = cssExports;
