// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Layout': string;
  'Layout__content': string;
  'Layout__content_opened': string;
  'Layout__sidebar': string;
  'Layout__sidebar_opened': string;
  'Layout__switcher': string;
  'Layout__switcher_opened': string;
}
declare var cssExports: CssExports;
export = cssExports;
