// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillsetStep': string;
  'SkillsetStep__input': string;
  'SkillsetStep__label': string;
  'SkillsetStep__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
