// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SignUpBlock': string;
  'SignUpBlock__item': string;
  'SignUpBlock__itemIcon': string;
  'SignUpBlock__itemTitle': string;
  'SignUpBlock__items': string;
  'SignUpBlock__submit': string;
  'SignUpBlock__submitLabel': string;
  'SignUpBlock__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
