// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Welcome': string;
  'Welcome__button': string;
  'Welcome__buttonLabel': string;
  'Welcome__footer': string;
  'Welcome__image': string;
  'Welcome__paragraph': string;
  'Welcome__text': string;
  'Welcome__title': string;
  'Welcome__title_archive': string;
  'Welcome__title_greeting': string;
  'Welcome__title_icon': string;
  'Welcome__title_list': string;
  'Welcome__title_mission': string;
  'Welcome__title_route': string;
}
declare var cssExports: CssExports;
export = cssExports;
