// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourceHeader': string;
  'ResourceHeader__back': string;
  'ResourceHeader__item': string;
  'ResourceHeader__label': string;
  'ResourceHeader_fixed': string;
}
declare var cssExports: CssExports;
export = cssExports;
