// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Page__logo': string;
  'Page__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
