// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Page': string;
  'Page_withSidebar': string;
}
declare var cssExports: CssExports;
export = cssExports;
