// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillsSuggestion': string;
  'SkillsSuggestion__body': string;
  'SkillsSuggestion__header': string;
  'SkillsSuggestion__row': string;
  'SkillsSuggestion__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
