// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Tabs': string;
  'Tabs__control': string;
  'Tabs__control_active': string;
  'Tabs__controls': string;
}
declare var cssExports: CssExports;
export = cssExports;
