version: '3.3'

services:
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile.prod
    volumes:
      - landing:/app/out
    working_dir: /app
    expose:
      - 3000
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - landing:/app/out
    environment: 
      - PORT=3000
      - DB_CONNECTION
    working_dir: /app
    expose:
      - 3000
    restart: always

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    volumes:
      - landing:/var/www/landing
    ports:
      - 80:80
    depends_on:
      - landing
      - backend
    restart: always

volumes:
  landing:

