version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    user: $USER_ID:$GROUP_ID
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - sh.local

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=skillhunter
      - POSTGRES_USER=skillhunter
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=-N
    user: $USER_ID:$GROUP_ID
    networks:
      default:
        aliases:
          - postgres.sh.local
