version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    expose:
      - 3000
    user: $USER_ID:$GROUP_ID
    environment:
      - HOME=/app/.home
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=skillhunter
      - POSTGRES_USER=skillhunter
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=-N

  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    volumes:
      - ./landing:/app
      - landing-static:/app/static
    working_dir: /app
    expose:
      - 3000
    user: $USER_ID:$GROUP_ID
    environment:
      - HOME=/app/.home

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - landing-static:/var/www/landing/static
    ports:
      - 80:80
    depends_on:
      - landing
      - backend

  hasura-db:
    image: postgres:11.2-alpine
    volumes:
      - hasura-db:/var/lib/postgresql/data
  
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha42
    ports:
      - 8080:8080
    volumes: 
      - ./qraphql/migrations:/hasura-migrations 
    depends_on:
      - hasura-db
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@hasura-db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

volumes:
  landing-static:
  postgres-data:
  hasura-db:

