version: '3.4'

services:
  proxy:
    build: ./proxy
    volumes:
      - landing:/var/www/landing
      - web_app:/var/www/web_app
      - admin_panel:/var/www/admin_panel
      - static:/var/www/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - landing
      - web_app
      - backend
    restart: always
    networks:
      - SkillHunter

  landing:
    build: ./landing
    volumes:
      - landing:/app/out
    working_dir: /app
    networks:
      - SkillHunter

  web_app:
    build: ./web
    volumes:
      - web_app:/app/dist
    working_dir: /app
    networks:
      - SkillHunter

  admin_panel:
    build: ./admin
    volumes:
      - admin_panel:/app/dist
    working_dir: /app
    networks:
      - SkillHunter

  backend:
    build: ./backend
    volumes:
      - landing:/app/out
      - static:/app/src/static
    env_file:
      - prod.env
    working_dir: /app
    ports:
      - 4321:4321
    restart: always
    networks:
      - SkillHunter
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/opt/bitnami/redis/etc/redis.conf
    networks:
      - SkillHunter

volumes:
  landing:
  web_app:
  admin_panel:
  static:
  redis_data:

networks:
  SkillHunter:
