version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    expose:
      - 4000
    user: $USER_ID:$GROUP_ID
    environment:
      - HOME=/app/.home
      - DB_CONNECTION=postgres://skillhunter:skillhunter@postgres:5432/skillhunter
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    env_file: 
      - .env.dev
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=-N

  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    volumes:
      - ./landing:/app
    working_dir: /app
    expose:
      - 3000
    user: $USER_ID:$GROUP_ID
    environment:
      - HOME=/app/.home

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - landing
      - backend

volumes:
  postgres-data:

