version: '3.4'

services:
  proxy:
    build: ./proxy
    volumes:
      - landing:/var/www/landing
      - web_app:/var/www/web_app
      - admin_panel:/var/www/admin_panel
      - static:/var/www/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - landing
      - web_app
      - backend
    restart: always

  landing:
    build: ./landing
    volumes:
      - landing:/app/out
    working_dir: /app

  web_app:
    build: ./web
    volumes:
      - web_app:/app/dist
    working_dir: /app

  admin_panel:
    build: ./admin
    volumes:
      - admin_panel:/app/dist
    working_dir: /app

  backend:
    build: ./backend
    volumes:
      - landing:/app/out
      - static:/app/src/static
    environment:
      - DOMAIN=skillhunter.io
      - PORT=4000
      - GOOGLE_CLIENT_ID=71152846727-1i6m8nnkch3morlj2o5fq0jfug55piu9.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=Fuph7bjuvg_8bVnc4QQu5QG3
      - FACEBOOK_CLIENT_ID=2147135318727842
      - FACEBOOK_CLIENT_SECRET=cd99bb88dee8c6a5a897adb5606fc949
      - FACEBOOK_CALLBACK_URL=https://app.skillhunter.io/api/auth/facebook/callback
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB

    working_dir: /app
    ports:
      - 4000:4000
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.dev
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=-N
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB

volumes:
  pgdata:
  landing:
  web_app:
  admin_panel:
  static:
