version: '3.3'

services:
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile.prod
    volumes:
      - landing:/app/out
    working_dir: /app
    expose:
      - 3000
    restart_policy:
      condition: on-failure

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - landing:/app/out
    environment: 
      - PORT=3000
    working_dir: /app
    expose:
      - 3000
    restart_policy:
      condition: on-failure

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    volumes:
      - landing:/var/www/landing
    ports:
      - 80:80
    depends_on:
      - landing
    restart_policy:
      condition: on-failure

volumes:
  landing:

