version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    expose:
      - 3000
    user: $USER_ID:$GROUP_ID
    environment:
      - HOME=/app/.home
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=skillhunter
      - POSTGRES_USER=skillhunter
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=-N

  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    volumes:
      - ./landing:/app
      - landing-static:/app/static
    working_dir: /app
    expose:
      - 3000
    user: $USER_ID:$GROUP_ID
    environment:
      - HOME=/app/.home

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - landing-static:/var/www/landing/static
    ports:
      - 80:80
    depends_on:
      - landing
      - backend

volumes:
  landing-static:
  postgres-data:

