// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Resource': string;
  'Resource__footer': string;
  'Resource__info': string;
  'Resource__infoIcon': string;
  'Resource__infoItem': string;
  'Resource__infoLink': string;
  'Resource__skills': string;
  'Resource__skillsItem': string;
  'Resource__skillsTitle': string;
  'Resource__title': string;
  'Resource__watch': string;
  'Resource__watchLabel': string;
}
declare var cssExports: CssExports;
export = cssExports;
