// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Mock': string;
  'Mock__text': string;
  'Mock__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
