// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AutoComplete': string;
  'AutoComplete__item': string;
  'AutoComplete__list': string;
}
declare var cssExports: CssExports;
export = cssExports;
