// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Resource': string;
  'Resource__content': string;
  'Resource__favicon': string;
  'Resource__header': string;
  'Resource__site': string;
  'Resource__status': string;
  'Resource__status_backlog': string;
  'Resource__status_done': string;
  'Resource__status_plan': string;
  'Resource__title': string;
  'Resource_article': string;
}
declare var cssExports: CssExports;
export = cssExports;
