// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Mark': string;
  'Mark_blue': string;
  'Mark_green': string;
  'Mark_orange': string;
}
declare var cssExports: CssExports;
export = cssExports;
