// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Header': string;
  'Header__content': string;
  'Header__section': string;
}
declare var cssExports: CssExports;
export = cssExports;
