// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillsetForm': string;
  'SkillsetForm__footer': string;
  'SkillsetForm__input': string;
  'SkillsetForm__label': string;
}
declare var cssExports: CssExports;
export = cssExports;
