// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'HelpToStart': string;
  'HelpToStart__body': string;
  'HelpToStart__footer': string;
  'HelpToStart__fullscreen': string;
  'HelpToStart__header': string;
  'HelpToStart__icon': string;
  'HelpToStart__section': string;
  'HelpToStart__section_active': string;
  'HelpToStart__section_done': string;
  'HelpToStart__submit': string;
  'HelpToStart__text': string;
  'HelpToStart__title': string;
  'HelpToStart__video': string;
}
declare var cssExports: CssExports;
export = cssExports;
