// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourceInfo': string;
  'ResourceInfo__icon': string;
  'ResourceInfo__item': string;
  'ResourceInfo__item_upperCase': string;
  'ResourceInfo__link': string;
}
declare var cssExports: CssExports;
export = cssExports;
