// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Icon': string;
  'Icon__heart': string;
  'Icon__heartFilled': string;
  'Icon__share': string;
}
declare var cssExports: CssExports;
export = cssExports;
