// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Icon': string;
  'Icon_active': string;
  'Icon_free': string;
  'Icon_lg': string;
  'Icon_xl': string;
}
declare var cssExports: CssExports;
export = cssExports;
