// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Login': string;
  'Login__btn': string;
  'Login__btn_fb': string;
  'Login__btn_google': string;
  'Login__description': string;
  'Login__footer': string;
  'Login__label': string;
  'Login__link': string;
  'Login__logo': string;
  'Login__security': string;
  'Login__terms': string;
  'Login__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
