// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourcePreview': string;
  'ResourcePreview__col': string;
  'ResourcePreview__col_actions': string;
  'ResourcePreview__col_info': string;
  'ResourcePreview__col_status': string;
  'ResourcePreview__control': string;
  'ResourcePreview__likes': string;
  'ResourcePreview__menu': string;
  'ResourcePreview__status': string;
  'ResourcePreview__status_backlog': string;
  'ResourcePreview__status_done': string;
  'ResourcePreview__status_plan': string;
}
declare var cssExports: CssExports;
export = cssExports;
