// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillSetCreator': string;
  'SkillSetCreator__desc': string;
}
declare var cssExports: CssExports;
export = cssExports;
