// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Settings': string;
  'Settings__content': string;
  'Settings__section': string;
}
declare var cssExports: CssExports;
export = cssExports;
