// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UserProfessions': string;
  'UserProfessions__item': string;
  'UserProfessions__item_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
