// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Notification': string;
  'Notification__close': string;
  'Notification__text': string;
  'Notification__text_error': string;
  'Notification__text_success': string;
  'Notification__text_warning': string;
  'Notification__timer': string;
  'showNotification': string;
}
declare var cssExports: CssExports;
export = cssExports;
