// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Skill': string;
  'Skill__body': string;
  'Skill__button': string;
  'Skill__footer': string;
  'Skill__header': string;
  'Skill__switcher': string;
  'Skill__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
