// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Search': string;
  'Search__input': string;
}
declare var cssExports: CssExports;
export = cssExports;
