// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Search': string;
  'Search__clear': string;
  'Search__form': string;
  'Search__input': string;
  'Search__switcher': string;
  'Search_opened': string;
}
declare var cssExports: CssExports;
export = cssExports;
