// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Content': string;
  'Content__text': string;
  'Content__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
