export enum ActivityActionTypes {
  SAGA_GET_SKILLSET_ACTIVITY = 'saga/GET_SKILLSET_ACTIVITY',
  SAGA_GET_SKILL_ACTIVITY = 'saga/GET_SKILL_ACTIVITY',

  SET_SKILLSET_ACTIVITY = 'SET_SKILLSET_ACTIVITY',
  SET_SKILL_ACTIVITY = 'SET_SKILL_ACTIVITY',
}
