export enum ResourcesActionTypes {
  SAGA_GET_RESOURCES = 'saga/GET_RESOURCES',

  SAGA_ADD_RESOURCE = 'saga/ADD_RESOURCE',

  SAGA_UPDATE_RESOURCE = 'saga/UPDATE_RESOURCE',
  SAGA_CHANGE_RESOURCE_LIKE_STATUS = 'saga/CHANGE_RESOURCE_LIKE_STATUS',
  SAGA_REMOVE_RESOURCE = 'saga/REMOVE_RESOURCE',

  SET_RESOURCES = 'SET_RESOURCES',
  ADD_RESOURCE = 'ADD_RESOURCE',
  UPDATE_RESOURCE = 'UPDATE_RESOURCE',
  CHANGE_RESOURCE_LIKE_STATUS = 'CHANGE_RESOURCE_LIKE_STATUS',
  REMOVE_RESOURCE = 'REMOVE_RESOURCE',
}
