export enum ResourcesActionTypes {
  SAGA_GET_RESOURCES = 'saga/GET_RESOURCES',
  SAGA_REMOVE_RESOURCE = 'saga/REMOVE_RESOURCE',
  SAGA_ADD_RESOURCE = 'saga/ADD_RESOURCE',
  SET_RESOURCES = 'SET_RESOURCES',
  ADD_RESOURCE = 'ADD_RESOURCE',
  REMOVE_RESOURCE = 'REMOVE_RESOURCE',
}
