export enum SkillsActionTypes {
  SAGA_GET_SKILLS = 'saga/GET_SKILLS',
  SAGA_ADD_SKILLS = 'saga/ADD_SKILLS',
  SAGA_REMOVE_SKILLS = 'saga/REMOVE_SKILLS',

  SET_SKILLS_DATA = 'SET_SKILLS_DATA',
  ADD_SKILLS = 'ADD_SKILLS',
  UPDATE_SKILLS_DATA = 'UPDATE_SKILLS_DATA',
  REMOVE_SKILLS = 'REMOVE_SKILLS',
}
