export enum TicketsActionTypes {
  SAGA_GET_TICKETS = 'saga/GET_TICKETS',
  SET_TICKETS = 'SET_TICKETS',
  SET_TICKETS_CURRENCY = 'SET_TICKETS_CURRENCY',
  SET_TICKETS_FILTER = 'SET_TICKETS_FILTER',
  SET_TICKETS_LOADING = 'SET_TICKETS_LOADING',
  SET_TICKETS_ERROR = 'SET_TICKETS_ERROR',
}
