export enum UserActionTypes {
  SAGA_GET_USER = 'saga/GET_USER',
  SAGA_REMOVE_USER_SKILLSET = 'saga/REMOVE_USER_SKILLSET',
  SAGA_ADD_USER_SKILLSET = 'saga/ADD_USER_SKILLSET',

  SET_USER_DATA = 'SET_USER_DATA',
  UPDATE_USER_DATA = 'UPDATE_USER_DATA',
  REMOVE_USER_SKILLSET = 'REMOVE_USER_SKILLSET',
}
