export enum UserSkillActionTypes {
  SAGA_GET_USER_SKILL = 'saga/GET_USER_SKILL',
  SAGA_ADD_RESOURCE_TO_USER_SKILL = 'saga/ADD_RESOURCE_TO_USER_SKILL',

  SET_USER_SKILL = 'SET_USER_SKILL',
  ADD_RESOURCE_TO_USER_SKILL = 'ADD_RESOURCE_TO_USER_SKILL',
}
