export enum UserSettingsActionTypes {
  SAGA_GET_USER_SETTINGS = 'saga/GET_USER_SETTINGS',
  SAGA_UPDATE_USER_SETTINGS = 'saga/UPDATE_USER_SETTINGS',

  SET_USER_SETTINGS = 'SET_USER_SETTINGS',
  UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS',
}
