// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'RoadMap': string;
  'RoadMap__item': string;
  'RoadMap__itemIcon': string;
  'RoadMap__itemText': string;
  'RoadMap__itemTitle': string;
}
declare var cssExports: CssExports;
export = cssExports;
