// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Checkbox': string;
  'Checkbox__content': string;
  'Checkbox__indicator': string;
  'Checkbox__input': string;
}
declare var cssExports: CssExports;
export = cssExports;
