// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UpdatePage': string;
  'UpdatePage__img': string;
  'UpdatePage__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
