// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Loader': string;
  'Loader__line': string;
  'Loader__line__orange': string;
  'Loader__line_blue': string;
  'Loader__line_green': string;
  'Loader_s': string;
}
declare var cssExports: CssExports;
export = cssExports;
