// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Filters': string;
  'Filters__item': string;
}
declare var cssExports: CssExports;
export = cssExports;
