// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SearchResults': string;
  'SearchResults__content': string;
  'SearchResults__empty': string;
}
declare var cssExports: CssExports;
export = cssExports;
