// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MobileMenu': string;
  'MobileMenu__avatar': string;
  'MobileMenu__control': string;
  'MobileMenu__control_add': string;
  'MobileMenu__control_home': string;
  'MobileMenu__control_library': string;
  'MobileMenu__control_profile': string;
  'MobileMenu__control_search': string;
}
declare var cssExports: CssExports;
export = cssExports;
