// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Resources': string;
  'Resources__col': string;
  'Resources__col_actions': string;
  'Resources__col_full': string;
  'Resources__col_info': string;
  'Resources__col_status': string;
  'Resources__creator': string;
  'Resources__header': string;
}
declare var cssExports: CssExports;
export = cssExports;
