export const HOME_ROUTE = '/'
export const REGISTRATION_ROUTE = '/registration'
export const AGREEMENT_ROUTE = '/agreement'
export const COOKIE_ROUTE = '/cookie'
export const PRIVACY_ROUTE = '/privacy'
export const FINAL_ROUTE = '/final'
