// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Layout': string;
  'Layout__aside': string;
  'Layout__container': string;
  'Layout__content': string;
  'Layout__footer': string;
  'Layout__main': string;
  'Layout__section': string;
}
declare var cssExports: CssExports;
export = cssExports;
