// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourceContent': string;
  'ResourceContent__date': string;
  'ResourceContent__img': string;
  'ResourceContent__text': string;
}
declare var cssExports: CssExports;
export = cssExports;
