// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UserSkillSet': string;
  'UserSkillSet__item': string;
  'UserSkillSet__link': string;
  'UserSkillSet__link_active': string;
  'UserSkillSet__list': string;
  'UserSkillSet__remove': string;
  'UserSkillSet__selected': string;
  'UserSkillSet__selectedArrow': string;
  'UserSkillSet__title': string;
  'UserSkillSet__userIcon': string;
}
declare var cssExports: CssExports;
export = cssExports;
