// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UserSkillset': string;
  'UserSkillset__create': string;
  'UserSkillset__item': string;
  'UserSkillset__link': string;
  'UserSkillset__link_active': string;
  'UserSkillset__list': string;
  'UserSkillset__remove': string;
  'UserSkillset__selected': string;
  'UserSkillset__selectedArrow': string;
  'UserSkillset__title': string;
  'UserSkillset__userIcon': string;
}
declare var cssExports: CssExports;
export = cssExports;
