// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourcePreviewStatus': string;
  'ResourcePreviewStatus_opened': string;
}
declare var cssExports: CssExports;
export = cssExports;
