// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'OnBoarding': string;
  'OnBoarding__icon': string;
}
declare var cssExports: CssExports;
export = cssExports;
