// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Status': string;
  'Status_backlog': string;
  'Status_done': string;
  'Status_plan': string;
}
declare var cssExports: CssExports;
export = cssExports;
