// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Status': string;
  'Status__icon': string;
}
declare var cssExports: CssExports;
export = cssExports;
