// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Onboarding': string;
  'Onboarding__button': string;
  'Onboarding__footer': string;
  'Onboarding__img': string;
  'Onboarding__subtitle': string;
  'Onboarding__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
