// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Table': string;
  'Table__cell': string;
  'Table__table': string;
  'Table__tr': string;
}
declare var cssExports: CssExports;
export = cssExports;
