// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MenuItem': string;
  'MenuItem_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
