// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Dropdown': string;
  'Dropdown__enter': string;
  'Dropdown__enter_active': string;
  'Dropdown__exit': string;
  'Dropdown__exit_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
