// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FoundResource': string;
  'FoundResource__content': string;
  'FoundResource__link': string;
}
declare var cssExports: CssExports;
export = cssExports;
