// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourceStatus': string;
  'ResourceStatus_opened': string;
}
declare var cssExports: CssExports;
export = cssExports;
