// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillStep': string;
  'SkillStep__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
