// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Layout': string;
  'Layout__caption': string;
  'Layout__content': string;
  'Layout__subtitle': string;
  'Layout__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
