// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UserSkillHeader': string;
  'UserSkillHeader__link': string;
  'UserSkillHeader__link_more': string;
  'UserSkillHeader__menu': string;
  'UserSkillHeader__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
