export const START_TELEGRAM_COMMAND = '/start'
export const LOGOUT_TELEGRAM_COMMAND = '/logout'
export const SKILLSET_TELEGRAM_COMMAND = '/skillset'
export const SKILL_TELEGRAM_COMMAND = '/skill'

export const TELEGRAM_COMMANDS = [
  LOGOUT_TELEGRAM_COMMAND,
  SKILLSET_TELEGRAM_COMMAND,
  SKILL_TELEGRAM_COMMAND,
]
