// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UserProgress': string;
  'UserProgress__bar': string;
  'UserProgress__label': string;
  'UserProgress__status': string;
  'UserProgress__status_bad': string;
  'UserProgress__status_good': string;
  'UserProgress__value': string;
}
declare var cssExports: CssExports;
export = cssExports;
