// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Auth': string;
  'Auth__btn': string;
  'Auth__btn_fb': string;
  'Auth__btn_google': string;
  'Auth__container': string;
  'Auth__description': string;
  'Auth__faq': string;
  'Auth__faqCol': string;
  'Auth__faqRow': string;
  'Auth__label': string;
  'Auth__link': string;
  'Auth__login': string;
  'Auth__logo': string;
  'Auth__security': string;
  'Auth__terms': string;
}
declare var cssExports: CssExports;
export = cssExports;
