// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillSet': string;
  'SkillSet__back': string;
  'SkillSet__button': string;
  'SkillSet__caption': string;
  'SkillSet__input': string;
  'SkillSet__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
