// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Skillset': string;
  'Skillset__input': string;
  'Skillset__label': string;
  'Skillset__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
