// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'NotFound': string;
  'NotFound__img': string;
  'NotFound__label': string;
  'NotFound__link': string;
  'NotFound__submit': string;
  'NotFound__submitLabel': string;
  'NotFound__subtitle': string;
  'NotFound__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
