// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UserSkill': string;
  'UserSkill__caption': string;
  'UserSkill__empty': string;
  'UserSkill__link': string;
  'UserSkill__link_more': string;
  'UserSkill__menu': string;
  'UserSkill__switcher': string;
  'UserSkill__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
