// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ShowSubscribe': string;
  'Subscribe': string;
  'Subscribe__field': string;
  'Subscribe__field_invalid': string;
  'Subscribe__text': string;
  'Subscribe__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
