FROM node:8-alpine

WORKDIR /app

COPY *.json /app/
COPY *.js /app/
COPY pages/ /app/pages/
COPY static/ /app/static/
COPY styles/ /app/styles/
COPY components/ /app/components/
COPY constants/ /app/constants/

USER root
RUN chmod 777 /app/landing
RUN chmod 777 /app/landing/*
RUN chmod 777 /app/*
RUN chmod 777 /app/

RUN npm ci
RUN npm run build
RUN npm run export
