// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'RecommendedResource': string;
  'RecommendedResource__add': string;
  'RecommendedResource__favicon': string;
  'RecommendedResource__info': string;
  'RecommendedResource__source': string;
}
declare var cssExports: CssExports;
export = cssExports;
