// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Profession': string;
  'Profession__input': string;
}
declare var cssExports: CssExports;
export = cssExports;
