// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'NotificationSettings': string;
  'NotificationSettings__desc': string;
  'NotificationSettings__item': string;
  'NotificationSettings__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
