// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillSearchList': string;
  'SkillSearchList__checkbox': string;
  'SkillSearchList__content': string;
  'SkillSearchList__row': string;
  'SkillSearchList__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
