// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'RemoveSkillSet': string;
  'RemoveSkillSet__button': string;
  'RemoveSkillSet__content': string;
}
declare var cssExports: CssExports;
export = cssExports;
