// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'RemoveSkillset': string;
  'RemoveSkillset__button': string;
  'RemoveSkillset__content': string;
}
declare var cssExports: CssExports;
export = cssExports;
