// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Resources': string;
  'Resources__header': string;
}
declare var cssExports: CssExports;
export = cssExports;
