// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SkillList': string;
  'SkillList__back': string;
  'SkillList__button': string;
  'SkillList__caption': string;
  'SkillList__input': string;
  'SkillList__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
