// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ResourceCreator': string;
  'ResourceCreator__control': string;
  'ResourceCreator__control_active': string;
  'ResourceCreator__controls': string;
  'ResourceCreator__desc': string;
  'ResourceCreator__field': string;
  'ResourceCreator__form': string;
  'ResourceCreator__input': string;
}
declare var cssExports: CssExports;
export = cssExports;
