// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CopySkillset': string;
  'CopySkillset__button': string;
  'CopySkillset__content': string;
}
declare var cssExports: CssExports;
export = cssExports;
