// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Menu': string;
  'Menu__button': string;
  'Menu__list': string;
  'Menu__list_left': string;
}
declare var cssExports: CssExports;
export = cssExports;
