// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Skills': string;
  'Skills__body': string;
  'Skills__btn': string;
  'Skills__checkbox': string;
  'Skills__header': string;
  'Skills__item': string;
}
declare var cssExports: CssExports;
export = cssExports;
