// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Skillset': string;
  'Skillset__btn': string;
  'Skillset__btnLabel': string;
  'Skillset__empty': string;
  'Skillset__emptyText': string;
}
declare var cssExports: CssExports;
export = cssExports;
