// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Footer': string;
  'Footer__copyright': string;
  'Footer__copyrightText': string;
  'Footer__link': string;
  'Footer__links': string;
}
declare var cssExports: CssExports;
export = cssExports;
