// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UserResource': string;
  'UserResource__content': string;
  'UserResource__control': string;
  'UserResource__control_more': string;
  'UserResource__controls': string;
  'UserResource__favicon': string;
  'UserResource__header': string;
  'UserResource__info': string;
  'UserResource__likes': string;
  'UserResource__select': string;
  'UserResource__sidebar': string;
  'UserResource__site': string;
  'UserResource__status': string;
  'UserResource__status_backlog': string;
  'UserResource__status_done': string;
  'UserResource__status_plan': string;
  'UserResource__title': string;
  'UserResource_article': string;
}
declare var cssExports: CssExports;
export = cssExports;
