// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Banner': string;
  'Banner__description': string;
  'Banner__subtitle': string;
  'Banner__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
