// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Notifications': string;
  'Notifications__item': string;
  'showNotificaion': string;
}
declare var cssExports: CssExports;
export = cssExports;
