// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Popup': string;
  'Popup__overlay': string;
}
declare var cssExports: CssExports;
export = cssExports;
