// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ProgressBar': string;
  'ProgressBarDone': string;
  'ProgressBar_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
