// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ProgressBar': string;
  'ProgressBar__enter': string;
  'ProgressBar__enter_active': string;
  'ProgressBar__exit': string;
  'ProgressBar__exit_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
